chore: new tag with dtk
linuxdeepin/dde-polkit-agent pull request #155
Opened 2023-08-01 08:01 UTC by Decodetalkers

Log:

2023-08-01 08:02 UTC, Decodetalkers commented
跟随dtk的版本追加tag

2023-08-01 08:04 UTC, BLumia commented on debian/changelog
> +dde-polkit-agent (6.0.4) unstable; urgency=medium
后边不需要空行吗？

2023-08-01 08:05 UTC, Decodetalkers commented on debian/changelog
> +dde-polkit-agent (6.0.4) unstable; urgency=medium
没注意

2023-08-01 08:21 UTC, wineee requested changes

2023-08-01 08:21 UTC, wineee commented on debian/changelog
> + -- chenhongtao <chenhongtao@uniontech.com>  Thu, 20 Apr 2023 16:54:37 +0800
为什么改历史 tag

2023-08-01 08:23 UTC, Decodetalkers commented on debian/changelog
> + -- chenhongtao <chenhongtao@uniontech.com>  Thu, 20 Apr 2023 16:54:37 +0800
因为写错了

2023-08-07 10:05 UTC, wineee commented
这个 tag 仍然没有合入，有什么阻碍吗？

2023-08-07 10:56 UTC, Decodetalkers commented
> 这个 tag 仍然没有合入，有什么阻碍吗？

啊，忘记它的存在了

2023-08-08 01:31 UTC, BLumia approved these changes

2023-08-08 01:32 UTC, BLumia commented
记得提集成（

2023-08-08 01:39 UTC, Decodetalkers commented
/Intergate

2023-08-08 01:39 UTC, Decodetalkers commented
/integrate

2023-08-08 06:34 UTC, merged